### PR TITLE
fix: mark deps as up-to-date when using stable

### PR DESCRIPTION
**Pull request by mastilver**

### CODE REVIEW

**Comment by mastilver** [comment]
@satazor @atduarte Is there something I can do to move this forward?

**Comment by satazor** [comment]
Thanks for the PR!

**Comment by satazor** [comment]
I will deploy later tonight, so that I could monitor if it's working nicely for a few minutes.

**Comment by mastilver** [comment]
Thank you! :)

If it help: I've got  module which is using the latest `babel-runtime` but npms.io wants me to use the alpha version: https://api.npms.io/v2/package/dynamic-cdn-webpack-plugin

**Pull request merged**
