### PR TITLE
move aggregate step to couchdb [work-in-progress]

### PR DESCRIPTION
**Pull request by slang800**
Moving the aggregate step into a CouchDB map/reduce means that the results will be cached in-between runs, and only the documents that change will be recalculated. This should help us improve performance & reduce the delay between scoring cycles. Also, we get to remove the `scoring!aggregation` document

The `couchdb/couchdb.coffee` file will be moved into its own module before merging, and I'll compile the CoffeeScript (I just use it because it's faster to write).

### CODE REVIEW

**Comment by satazor** [comment]
Initially when I started implementing the aggregation I did it with a reduce function in CouchDB. Tough it was very slow to fully index it everytime I was changing it. I understand that after the view is done, the indexing is incremental but the aggregation is really fast on my laptop (around 10sec).

Also why coffee? :S

**Comment by slang800** [comment]
Hmm... that's strange. What version of Spidermonkey are you running within CouchDB? I've [heard](http://blog.npmjs.org/post/75707294465/new-npm-registry-architecture) that older versions have performance problems, but haven't tested it for myself on anything lower than `1.8.5`.

What sort of CPU load were you seeing while running that map/reduce and what were your process limits and total CPU cores?

Also, for development you could try running with a subset of the total modules if you just don't want to recalculate everything.

And CoffeeScript is much faster to write & edit... the shorthands like `in` and the existential operator `?` are easier to read, and the indentation-based syntax makes it nice and terse.

**Comment by satazor** [comment]
Hmm I don't know, I just use the default engine that comes with 1.6.1.

**Comment by satazor** [comment]
For instance, the app design document on the npm databes takes 4h to fully index :(

**Comment by satazor** [comment]
Bump.

**Comment by satazor** [comment]
Closing for now.. this doesn't bring a lot of benefit and it increases complexity by a great margin.

**Pull request closed without merging**
