### PR TITLE
Clean docs

### PR DESCRIPTION
**Pull request by slang800**
More cleaning with [tidy-markdown](http://github.com/slang800/tidy-markdown) & some spelling/grammar stuff.

### CODE REVIEW

**Comment by satazor** [comment]
Thanks again! I see that you are very interested in this project and that's good! Would you like to contribute with code?

**Comment by slang800** [comment]
Sure! Right now I'm just reading through all the code/docs and getting it set up on my machine.

**Comment by satazor** [comment]
Cool, let me know if you run into any problems. The analyzer is 100% done for the launch milestone and I'm just doing tests. Next will be the API and the website. Send me your email so that I can invite you into our slack channel.

**Comment by slang800** [comment]
My email is slang800@gmail.com, but I don't use Slack because it's non-free software with [good alternatives](https://drewdevault.com/2015/11/01/Please-stop-using-slack.html).

**Comment by satazor** [comment]
Well I see. At the moment we are using slack with a few integrations, such as `github` and `keymetrics` which we use to monitor the current production deployment hosted at scaleway.com. It would be difficult to migrate to IRC, specially because these integrations are so useful. Want me to send an invite anyway or?

**Comment by slang800** [comment]
I'm not familiar with keymetrics, but I know that there are [hubot scripts for GitHub](https://github.com/hubot-scripts/hubot-github-repo-event-notifier) which hook up to IRC. But anyway, I can probably just keep up w/ development here on GH.

**Pull request merged**
